apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
  creationTimestamp: "2024-07-02T00:30:03Z"
  resourceVersion: "2323"
  uid: 4b970a28-b803-4392-a3f0-03995396c901
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::ID-AWS:role/ng-prd-api-eks-node-group-20240702001022949700000003
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::ID-AWS:role/ng-prd-dados-eks-node-group-20240702001022948900000002
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::ID-AWS:role/codebuild-role
      username: build-user
